project:
  type: website
  output-dir: docs

website:
  title: "cocojiang.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: test.qmd
        text: Test

format:
  html:
    theme: minty
    #css: styles.css
    toc: true

editor: visual

